import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/Header/Header";
import { LoginModalProvider } from "@/context/LoginModalContext";
import { AuthStateProvider } from "@/context/AuthStateContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quickbet",
  description: "Generated by create next app",
};

export default function rootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthStateProvider>
          <LoginModalProvider>
            <Header />
            {children}
          </LoginModalProvider>
        </AuthStateProvider>
      </body>
    </html>
  );
}
